### ISSUE TITLE
Flickering in 0.28

### ISSUE THREAD

**Issue by ethereumdegen** [vladbat00/bevy_egui#295]
Updated this dependency  to 0.28.0 and now my fork of PLS editor has flickering on the egui windows

**Comment by mvlabat** [comment]
Hi. Could you help me with a minimal reproducible example with just using `bevy_egui`? So we can rule out issues on the PLS editor end.

**Comment by vladbat00** [comment]
I'll close the issue since I haven't got a response. But if the issue is still actual, feel free to comment/reopen.
