### ISSUE TITLE
update rustdoc to readme

### ISSUE THREAD

**Issue by mirsella** [vladbat00/bevy_egui#330]
https://vladbat00.github.io/bevy_egui_web_showcase/index.html gives a 404

**Comment by vladbat00** [comment]
Hm, I can't reproduce it. I changed my nickname not so long ago, the previous link was https://mvlabat.github.io/bevy_egui_web_showcase/index.html, which is now 404. Where I forgot to update the link though is https://github.com/vladbat00/bevy_egui/blob/581a0e1b423e3fae4d3a011c08c8d8000702b544/src/lib.rs. And it's not the only inconsistency with the current readme file... Maybe you were checking the link from docs.rs (which reads the contents from `src/lib.rs`)?

**Comment by mirsella** [comment]
ohhh yes thats it

**Comment by vladbat00** [comment]
Fixed in #333, thanks
