### ISSUE TITLE
[minor] github.io example usage website is dead

### ISSUE THREAD

**Issue by dylanopen** [vladbat00/bevy_egui#335]
Hi!
Just wanted to let you know that the https://mvlabat.github.io/bevy_egui_web_showcase example crate showcase shown on your docs.rs homepage has moved to vladbat00...

It seems as though you must have changed your username, maybe change the link in your docs.rs page so people aren't confused!

![Screenshot_20241212_180448](https://github.com/user-attachments/assets/dff41463-2449-4389-a32c-48df9c223b76)

**Comment by vladbat00** [comment]
Fixed in #333, thanks

**Comment by dylanopen** [comment]
For those interested, I fixed this in #336

**Comment by vladbat00** [comment]
Oh, my bad, didn't mean to misattribute! (Miss-clicked an autocompletion link probably.)
