### ISSUE TITLE
already borrowed: BorrowMutError

### ISSUE THREAD

**Issue by OskarMihalik** [vladbat00/bevy_egui#342]
# Errors
`already borrowed: BorrowMutError`
![image](https://github.com/user-attachments/assets/ecf24aa3-67e8-46c9-bf4c-e0d5b61ba571)
and
`Uncaught RuntimeError: unreachable executed
    __wbg_adapter_55 https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:291
    real https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:199
    __wbg_new_4b15073a88792687 https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:1385
    handleError https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:44
    __wbg_new_4b15073a88792687 https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:1384
    __wbg_finalize_init https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:2282
    __wbg_init https://oskarmihalik.github.io/bevy_template_egui/bevy_game-4462080ca98d8ffb.js:2336
    async* https://oskarmihalik.github.io/bevy_template_egui/:139
bevy_game-4462080ca98d8ffb_bg.wasm:15316101:1
`

these errors cause the whole app to be unresponsive 
# how to reproduce:
You can reproduce it by using bevy_egui in browser using trunk serve using this template: https://github.com/NiklasEi/bevy_game_template

It works native, when running `cargo run`
# Related
The problem is maybe related to this egui issue: https://github.com/emilk/egui/issues/2812, but disabling bevy feature "multi_threaded" doesn't help

## reproducable example
I created a minimal reproducable example here:
repo: https://github.com/OskarMihalik/bevy_template_egui/settings/pages
github page: https://oskarmihalik.github.io/bevy_template_egui/

# OS
- pop os
- rustc 1.85.0-nightly (426d17342 2024-12-21)
- trunk 0.21.5

# Edit
It works if i use bevy 0.14 and bevy_egui 0.30

**Comment by OskarMihalik** [comment]
I found a fix, by putting 
```
[dependencies]
wasm-bindgen = "=0.2.97"
```
in cargo.toml, everything works as expected, dunno why i need to specify it like this...

**Comment by vladbat00** [comment]
Interesting, thanks for sharing! I wonder what breaks with newer versions of wasm-bindgen...

**Comment by OskarMihalik** [comment]
Yeah, strange thing is that i was able to build it before then I tried many things, after which i got version mismatch in wasm-bindgen (similar to this https://stackoverflow.com/questions/76452749/leptos-with-axum-issue-with-wasm-bindgen-versions)

It wasn't problem just on my PC, because the deployed version was made with github actions...
